default:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: ror_blog_app5
  username: postgres
  password: <%= ENV["ROR_BLOG_APP_DATABASE_PASSWORD"] %>
  host: localhost
test:
  <<:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: ror_blog_app5
  username: postgres
  password: <%= ENV["ROR_BLOG_APP_DATABASE_PASSWORD"] %>
  host: localhost
production:
  <<:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: null
  username: null
  password: null
  host: localhost